version: '2'

services:
  mariadb:
    # env_file:
    #   - ../env/custom/mariadb.env
    # volumes:
    #   - /path/to/app/mariadb/config:/etc/mysql-config
    #   - /path/to/app/mariadb/data:/var/lib/mysql/data

  redis:
    # env_file:
    #   - ../env/custom/redis.env
    # volumes:
    #   - /path/to/app/redis:/var/lib/redis/data

  minio:
    # env_file:
    #   - ../env/custom/minio.env
    # volumes:
    #   - /path/to/app/minio:/data/minio
  
  node:
    # volumes:
    #   - /path/to/php/app/html:/usr/src/app

  php:
    # env_file:
    #   - ../env/custom/php.env
    # volumes:
    #   - /path/to/php/app:/var/www
